### ISSUE TITLE
OT URNs not resolving or not listed correctly

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/cts#135]
I was checking proofs for an article and noticed some OT URNs not functioning properly.. 

urn:cts:copticLit:ot when put in the search box does not resolve.  The general URL  http://data.copticscriptorium.org/urn:cts:copticLit:ot does not resolve either

On [the corpus page](http://data.copticscriptorium.org/index/corpus/) the URN for sahidica.ruth is incorrectly listed as urn:cts:copticLit:ot . It should be urn:cts:copticLit:ot.ruth.coptot . It looks like the document URN is correct.

I don't know if this is related to an issue we previously closed https://github.com/CopticScriptorium/cts/issues/126

Thanks in advance for your help!

**Comment by lgessler** [comment]
Ruth should have its correct corpus URN listed [in the mappings file](https://github.com/CopticScriptorium/cts/blob/master/coptic/gh_ingest/name_mapping.tab). The error is coming from the fact that Ruth's automatically-assigned corpus URN (which as we know is unreliable) is identical to the old testament's URN, and our code assumes that no two corpora will have the same URN.

**Comment by ctschroeder** [comment]
Thanks Luke!

I think I’m not sure I understand. I don’t see Ruth in the linked mapping file. Are you saying that’s the problem?

**Comment by lgessler** [comment]
Oops, that "should" was ambiguous. I intended deontic _should_, not epistemic :) 

Yeah, I can't find the discussion where we decided this atm, but because it's impossible for us to automatically infer from a document URN what the correct corpus URN ought to be, we need to maintain an explicit list of them for every corpus in that file. I think @amir-zeldes's been maintaining it for the most part so far. I just added the line for Ruth and updated it in prod.

**Comment by amir-zeldes** [comment]
Thanks @lgessler - that is all correct, the corpus URN is not automatically deducible from anything, so it has to be mapped manually in this file: https://github.com/CopticScriptorium/cts/blob/master/coptic/gh_ingest/name_mapping.tab

Personally I'd prefer to see it be a corpus metadata, but that would mean we'd need to enter it and remember it for each corpus (it's probably like this because it's almost easier to have them all in this one file, and we must have launched this feature between releases, with corpora simply not having such a metadatum). BTW the same applies to corpus 'human' titles, which are specified in the same tab file.

**Comment by ctschroeder** [comment]
Got it @lgessler thanks! 

It's usually pretty easy to figure out what the corpus URN is manually, so I'm happy for either method. If it can be added to corpus metadata with validation that would be great. But won't we still need to enter it into the mapping file, since the architecture of the software is?

**Comment by amir-zeldes** [comment]
If we decide to go with corpus metadata, the architecture would need to be updated to reflect that (two mechanisms are a recipe for trouble)

**Comment by ctschroeder** [comment]
I think then for now we should stick with updating the file, unless you think we'll update the architecture . I will add it to the [wiki workflow](http://wiki.copticscriptorium.org/doku.php?id=basic_annotation_workflow)!

**Comment by ctschroeder** [comment]
Ok I updated the wiki.

**Comment by amir-zeldes** [comment]
Thanks!
