### ISSUE TITLE
"order" sorting mechanism using "order" metadatum not working

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/cts#143]
Documents in a corpus are appearing alphabetically, not according to the "order" metadatum. See for example [A22](http://data.copticscriptorium.org/texts/acephalous_work_22/) where the documents appear in alphabetical order, but the "order" metadatum puts them in a different order.

**Comment by lgessler** [comment]
Fixed in 5af92e2, which is now live. New behavior:

- For fully ordered corpora, the order metadatum is used to sort.
- For unordered corpora, the title is used to sort.
- For partially ordered corpora (like [shenoute.those](http://data.copticscriptorium.org/texts/shenoutethose/)), ordered documents are displayed first and unordered documents are displayed last, ordered by title.

Everything seems to be working OK, but please have a look yourself.

**Comment by ctschroeder** [comment]
Thank you! This looks good to me!
