### ISSUE TITLE
Instead of creating new ingest, simply expire current ingest

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#23]
If ingest is expired, when a user requests a text, update it in cache.

**Comment by lukehollis** [comment]
We'll need to be able to query ANNIS directly without initializing Vaadin for this to be feasible.  Otherwise the wait time for the user will be in the range of 30-60 seconds.

**Comment by amir-zeldes** [comment]
I’ll definitely look into the VAADIN issue, but where are you getting 30-60 seconds from? For me getting an ANNIS visualizer to render from the server takes about 2 seconds for a Bible chapter, and about 4 seconds for a long diplomatic manuscript. Where is the lag coming from?

**Comment by lukehollis** [comment]
The 30-60 is to guarantee not catching the loading window as Vaadin initializes.  Sometimes when the ingest queries a lot of texts via Selenium things slow down just a bit.  Maybe the larger HTML visualizations take a little longer?  As I watch Selenium (using Firefox driver), when it queries 10-15 texts in a row, it typically has to wait longer.  Could check on how Selenium's doing this as well--maybe it's doing something strange that would slow the Vaadin page load down.

**Comment by lukehollis** [comment]
Any luck with querying the HTML outside of Vaadin?  Just checking in on the status of how we might be able to use a work-around here.

**Comment by amir-zeldes** [comment]
Not yet, but I’m looking into it. I don’t expect it to be solved before Friday though, I’ll try to give you a prognosis once I have a better understanding and have spoken to the team in Berlin.

**Comment by lukehollis** [comment]
Some brainstorming on this:  what if we just loaded the HTML visualization from ANNIS with an iframe?  Might make for a less complicated and more sustainable app and showcase your student's work better.  Then the ingest would just be for the corpus and document metadata.  The HTML visualization ANNIS query would use the docname ingested from ANNIS and the HTML visualization slug specified on the corpus object in the resolver.

**Comment by lukehollis** [comment]
HTML now loaded from ANNIS embedvis on each document via an iframe as mentioned in https://github.com/CopticScriptorium/cts/issues/24

**Comment by lukehollis** [comment]
To follow up quickly here, it was decided that the HTML should not be loaded in an iframe or external window as mentioned in the previous comment because that would add an additional load on the ANNIS server and the vaadin client is somewhat slow to load the visualizations.  Until vaadin can serve HTML without executing client-side javascript, it seems like implementing an expiration for the current ingest as we were discussing here won't be scalable/sustainable.

**Comment by amir-zeldes** [comment]
I’m not clear on this – I thought we wanted to use expiration precisely because of ANNIS performance. This way, the data is only loaded after an update on demand, whenever someone happens to access, say 1 Corinthians 5, and the repo sees there’s a new version to load (and subsequently cache for next time). The alternative not using expiration is, after each update to query ANNIS for every single visualization of every single document, which puts an unnecessary load on the ANNIS server. That makes expiration sound better, or am I missing something?

**Comment by lukehollis** [comment]
Yes, we discussed the potential of this method, but during our discussion, I believe we came to the conclusion that until Vaadin can render the HTML visualization without executing client-side javascript, we should not rely on this method. This would be a non-trivial change to implement at this point in development.

**Comment by amir-zeldes** [comment]
I was not aware we discussed not doing this (hence the open issue). I've given this some thought, and I think this is actually critical, because otherwise we have 520 vis calls every ingest for sahidica alone (260* chapter view+analytic), and with a view to future expansion, not having the expiration strategy will lead to serious performance hits on the server. 

I understand that this could take some time and of course it is not realistic to have that done this week, but it definitely needs to be implemented for this site to run in a sustainable way.

**Comment by ctschroeder** [comment]
Yes, I thought this was core functionality we'd discussed since the beginning.

**Comment by lukehollis** [comment]
We discussed this as an option for the ingest, but for the implementation, this is not sustainable until Vaadin can render HTML without executing client-side Javascript.

**Comment by amir-zeldes** [comment]
I think I'm missing something - why does this depend on Vaadin not using Javascript? If the headless browser can query the visualizer on ingest, can't it do the same on an expired fetch request?

**Comment by lukehollis** [comment]
The extra time to execute the javascript for each visualization and load the HTML, then query the document metadata and factor that into the search fields with the splittable flag would be a cumbersome and lengthy process for the end user to experience.  I wouldn't advise it even if it were possible to get the HTML visualizations without executing client-side javascript, but that would take out the more major ~10-20 second wait time which would make this more feasible if you wanted to move forward in this way.   

I've been clear in my intentions about the expiration of the ingest on this ticket since March 13th.  I could work on the implementation of this, but it seems a bit extreme at this point to add this to the list of outstanding items.  Please let me know if this is mission-critical to this iteration of the URN resolver and visualization cache.

**Comment by amir-zeldes** [comment]
Like I said, I don't think it needs to happen this week, but as a plan, expiration is necessary for performance. I've been watching the sahidica corpus reimport with the corpus metadatum for over an hour wondering what was up, then I saw your other message and realized the ingest was running - this makes the import slow down to a crawl sadly (a stronger server would be nice...)

If the headless browser wait is the main delay, as I read from the older posts, maybe we can find a middle way. We could move back to the iframe solution or something similar, but once the iframe has been filled, save the result to cache and use that next time instead of calling the live ANNIS instance, until expiration kicks in and it has to be fetched again. That way, you don't have to wait for render, run the full caching mechanism, and only then show the cached result to the user after expiration. The expiration case will behave like the intended iframe case, and the cached case will fetch the data from the disk (but in the same sort of container - it will look the same to the user). Does that make sense?

On expiration, the ingest would still have to get metadata from ANNIS, but that can't be avoided, and the REST API is a lot less expensive than the visualizer calls.

**Comment by ctschroeder** [comment]
Hi, @lukehollis where are we on this?  Thanks.

**Comment by ctschroeder** [comment]
leaving open because of the issues discussed in 3 June 2015 meeting

**Comment by ctschroeder** [comment]
Leaving this open since it is operating but we may wish to modify the functionality.

**Comment by ctschroeder** [comment]
Further comments on the nature of the issue:
If something is updated in ANNIS and the ingest is “expired” but not re-ingested, the visualization that appears when a user clicks on the document vis is new/updated, but if there is new metadata, that new metadata doesn’t appear in the filtering menu.  The user would have to know there is a new annotator, etc. (metadata information).  AZ:  we need a metadata and document manifest ingest that needs to precede an expiration ingest [The metadata ingestion code already exists in the full ingest function; should be manageable to copy it over to the right place in the expiration ingest - AZ]

**Comment by amir-zeldes** [comment]
To clarify, I don't think the metadata ingest should be separate from the expiration ingest, I think the expiration ingest should be default refresh the document list and metadata for each expired corpus corpus.

**Comment by ctschroeder** [comment]
moved this from high priority to wontfix since being able to ingest data on a corpus by corpus basis fixes most of our problems.
