### ISSUE TITLE
Add relANNIS to URN spec & resolver

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#40]
I just need to know what the relANNIS URNs should look like, and I'll add them to the resolver.

**Comment by amir-zeldes** [comment]
There are too “ANNIS” objects to reference:

 

-        The search interface with the corpus selected (using the base64 parameter, e.g. A22: https://corpling.uis.georgetown.edu/annis/scriptorium#_c=c2hlbm91dGUuYTIy) 

-        The relANNIS files on github, if someone wants to import their corpus into their own ANNIS instance (server or local kickstarter): https://github.com/CopticScriptorium/corpora/tree/master/shenoute-a22/shenoute.a22_relANNIS 

 

I’m not sure if we need the second link as a separate thing from the general github link to the repo (then users can just pick what format they want). The first one is essential since it’s ontologically different and has a separate domain too. @ctschroeder what’s your preference?

**Comment by ctschroeder** [comment]
Hi,

On 3/17/15 7:48 PM, Amir Zeldes wrote:
> There are too “ANNIS” objects to reference:
>
>
>
> - The search interface with the corpus selected (using the base64 
> parameter, e.g. A22: 
> https://corpling.uis.georgetown.edu/annis/scriptorium#_c=c2hlbm91dGUuYTIy) 
>
>
> - The relANNIS files on github, if someone wants to import their 
> corpus into their own ANNIS instance (server or local kickstarter): 
> https://github.com/CopticScriptorium/corpora/tree/master/shenoute-a22/shenoute.a22_relANNIS 
>
>
Yes, exactly, this is what I meant by the query and the files.  The 
buttons to ANNIS on Luke's pages right now go to the search interface.
>
>
> I’m not sure if we need the second link as a separate thing from the 
> general github link to the repo (then users can just pick what format 
> they want). The first one is essential since it’s ontologically 
> different and has a separate domain too. @ctschroeder what’s your 
> preference?
>
I'm going to distinguish between links and URNs:

We definitely need links to the search interface.

We definitely need URNs for the relANNIS files.  Because we should 
provide canonical URNs for all of the manifestations of these documents 
in their different formats and visualizations, and the URN for, say, AOF 
( urn:cts:copticLit:shenoute.AOF )should bring a list of all AOF 
instances -- including relANNIS.  If we need to bill this as a separate 
thing, that's fine, but we should have resolvable relANNIS URNs, and 
those should come up on any list of URNs for their corresponding 
documents or classes of documents.  I apologize that these didn't make 
it into Bridget's table.  They are basically the same as the PAULA and 
TEI URNS -- just with relANNIS instead of PAULA/xml and TEI/xml in the 
URNs, and going to 
https://github.com/CopticScriptorium/corpora/tree/master/abraham/shenoute.abraham.our.father_relANNIS 
instead of 
https://github.com/CopticScriptorium/corpora/tree/master/abraham/shenoute.abraham.our.father_TEI.

My question is: do we need a canonical URN for the installation of a 
corpus in our ANNIS interface?  (e.g. 
urn:cts:copticLit:shenoute.AOF/corpling or 
urn:cts:copticLit:shenoute.AOF/ANNIS) which people could cite, and which 
would resolve to the relatively stable link 
http://corpling.uis.georgetown.edu/annis/scriptorium#_c=c2hlbm91dGUuYWJyYWhhbS5vdXIuZmF0aGVy. 
This is DEFINITELY outside the original project parameters.  But a good 
question nonetheless, I think.  Not urgent, but something to put on the 
longer list.

I think Amir's question is do we need to resolve the relANNIS canonical 
URNs to the GitHub link and do we need to foreground that (or even list 
it with a button) on the website as we do with TEI? We don't have 
buttons for the PAULA XML URNs on Luke's setup right now.  I think 
resolving it is a pretty trivial thing, no?  (It's a matter of adding it 
to whatever table is underlying these mappings, right?)  Whether we have 
a button on the website for every corpus is another question.  Currently 
on our corpora page we link only to the "latest" release of the corpora 
-- all of it:  PAULA, TEI, relANNIS all in one zipped downloadable 
file.  Let me think about whether we need buttons for PAULA and 
relANNIS.  But this is minor, to my mind.  We can always add the 
buttons.  The URNS are the major thing.

Take care,
Carrie

>
>
> From: Luke Hollis [mailto:notifications@github.com]
> Sent: Tuesday, March 17, 2015 21:27
> To: CopticScriptorium/cts
> Subject: [cts] Add relANNIS to URN spec & resolver (#40)
>
>
>
> I just need to know what the relANNIS URNs should look like, and I'll 
> add them to the resolver.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/CopticScriptorium/cts/issues/40> . 
> <https://github.com/notifications/beacon/ACFlWyIOWgF9IRP4iRihiiQQxJFDiFHBks5n2MvbgaJpZM4DwYPS.gif> 
>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/CopticScriptorium/cts/issues/40#issuecomment-82697985>.
>


-- 
________________________________
C. Schroeder
Associate Professor, Religious and Classical Studies
The University of the Pacific

carrie@carrieschroeder.com
http://www.carrieschroeder.com
https://pacific.academia.edu/CarolineSchroeder

Coptic SCRIPTORIUM
http://www.copticscriptorium.org

Blog
http://www.earlymonasticism.org

**Comment by lukehollis** [comment]
Added a reIANNIS placeholder to the URN resolver beneath "Cite this document".  Can build on this when we make more decisions in the future.

**Comment by lukehollis** [comment]
Updated the reIANNIS and ANNIS UI URNs per consensus specificiations.  Let me how this looks!

**Comment by ctschroeder** [comment]
yeah again I need to see a list of the URNs. We shouldn't be using doc names for the doc urns--we should be using something different.

**Comment by lukehollis** [comment]
reiANNIS is now relANNIS per @balmas's branch and commit: https://github.com/CopticScriptorium/cts/commit/6b14aa8397a187b3c2170dc51678a10cbc54c9b3

**Comment by ctschroeder** [comment]
looks fine in the paths; need a relANNIS button though

**Comment by lukehollis** [comment]
relANNIS button is added to the other links on each document:
![screenshot from 2015-05-14 10 21 43](https://cloud.githubusercontent.com/assets/2633382/7633583/0cf70e8a-fa23-11e4-9a83-9d0930a28514.png)
