### ISSUE TITLE
Rename Collection to Corpora and ingest corpus metadata from ANNIS

### ISSUE THREAD

**Issue by lukehollis** [CopticScriptorium/cts#60]
From @ctschroeder: "5. Get rid of the classification of "Collections" in Django and instead
call them "Corpora" and create each corpus based on the corpus metadata"

@amir-zeldes will add a Coptic Scriptorium flag to the corpora manifest in the Georgetown ANNIS that will mark which corpora the resolver will ingest.

**Comment by amir-zeldes** [comment]
Question @ctschroeder <https://github.com/ctschroeder> : what are we using for the flag? Options:

 

-        New metadatum (will then be visible in all manifestations of the corpus)

-        Some sort of hidden spec in ANNIS (not visible outside ANNIS, but requires ANNIS development)

-        Substring of a metadatum we use anyway (probably ‘project’, which  means only corpora that have a ‘project’ metadatum, containing substring ‘scriptorium’ case insensitive will be added)

 

I’m for 1 or 3, since ANNIS development is more of a bottleneck than the other two.

**Comment by ctschroeder** [comment]
Either 1 or 3 are fine with me, but what would be the advantage of 
adding a new metadata field (1) instead of using what we already have 
(3)?  I'm leaning toward 3 but open to 1 if you think there is an 
advantage to it that would justify the time of going in and adding the 
metadata to every corpus.

**Comment by lukehollis** [comment]
As I'm working on the implementation in the resolver for this, @ctschroeder and @amir-zeldes, I want to add a quick note here to say that if we ingest the corpus list and corpora metadata from ANNIS completely dynamically instead of the current model with a few pre-configured metadata fields related to each corpus, ANNIS will need metadata fields for the ANNIS corpus id string ("c2hlbm91dGUuYTIy" for the link https://corpling.uis.georgetown.edu/annis/scriptorium#_c=c2hlbm91dGUuYTIy), the Github repo link, and what types of HTML visualizations to query for documents related to it.  It seems like it might possibly be good for consistency and useful also to add a "corpus_cts_urn" metadata field to each corpus in the same manner as it's been added to the document-level metadata.  Let me know your thoughts about how feasible adding these metadata fields would be.  If we want to ingest all corpora and corpus metadata completely dynamically from ANNIS but adding these fields to ANNIS isn't an option, these fields (annis corpus id, github repo link, which html visualizations are supported for this corpus) could also be configured manually for each corpus after ingest.  

So far development for rewriting the ingest and restructuring/renaming the data model is coming along well on this issue, and I'll have another demo up for consideration as soon as I'm able.

**Comment by ctschroeder** [comment]
I think most of that should be possible, though I am not certain about: 
1. the ANNIS corpus id string (it's not my bailiwick, though my hunch is that if there is a string it should be possible)
2. *unique* cts urn's for the Bible corpora:  The cts system does not map one to one with our corpus architecture.  For example:  we have a sub-corpus of 1 Corinthians in the big unedited NT corpus as well as a corpus of 1 Corinthians that has been edited by a human.  BOTH of these corpora have the urn:  urn:cts:copticLit:nt.1cor.sahidica because both are the "Sahidica" editions of the Coptic book of 1 Corinthians (edited by Warren Wells et al.).  There can definitely be corpus level urn's, but they will not be UNIQUE.  What is UNIQUE is the ANNIS corpus string.  As I write this, I realize @balmas may want to weigh in on this:  all of this stuff is stuff we have edited (whether through machine-processed annotation or human+machine annotation), so perhaps these aren't really "Sahidica" editions, and perhaps the our human annotated 1 Cor is a different edition from the machine-only annotated 1 Cor.

**Comment by balmas** [comment]
@ctschroeder Maybe I'm misunderstanding, but didn't we decide that the edited Sahidica corpus would have a different URN?

So we have the "conceptual work" 1 Corinthians:
urn:cts:copticLit:nt.1cor

The uncurated edition (translation) of this work:

urn:cts:copticLit:nt.1cor.sahidica

And the curated edition (translation) of this work:
urn:cts:copticLit:nt.1cor.sahidica_ed

**Comment by ctschroeder** [comment]
You are right!  Thank you @balmas.  Should have checked the inventory.  My apologies.

**Comment by ctschroeder** [comment]
It does mean, however, that there is not a unique cts urn for the machine-processed Bible corpus.  Each book is urn:cts:copticLit:nt.1cor.sahidica urn:cts:copticLit:nt.2cor.sahidica etc.  These would function as urn's for the subcorpora but there is not one unique urn for the whole corpus.  I think Amir explained the subcorpora system to @lukehollis.  
Is it also possible to do this all as a substring of the document urn's?  urn:cts:copticLit:nt.1cor.sahidica:1 belongs to urn:cts:copticLit:nt.1cor.sahidica and urn:cts:copticLit:nt.1cor.sahidica_ed:1 belongs to urn:cts:copticLit:nt.1cor.sahidica_ed.  urn:cts:copticLit:shenoute.a22.monbya_421_428 belongs to urn:cts:copticLit:shenoute.a22 etc.

**Comment by amir-zeldes** [comment]
Just a quick note on the ANNIS flags for automated ingest:

 

-        We have decided on option 3, meaning that a metadatum name and value substring of our choosing, which should be configurable, will flag corpora for ingestion. The field will currently be: “project” and the value will be (case insensitive) /.*scriptorium.*/. From the repo perspective, we just need to flag a metadatum name and (case insensitive substring) value (or regex pattern as a value). That will allow us to revert to dedicated field if we ever wish to.

-        I need to think about the issue of getting the list of available visualizers per corpus. This is something ANNIS should be able to give you, since the service knows this, so I think we will expose an API for this (there might be one already, I need to check).

**Comment by lukehollis** [comment]
Okay, this sounds great--I've altered the data model to accommodate this change and will update the ingest when you send the info on the API my way.

**Comment by ctschroeder** [comment]
The corpus metadata and document metadata should all already have the project field information, so you should be all set with that, Luke.  
Also, regarding the whole unique identifier for corpora question that was also part of this thread: the corpora do all have names.

**Comment by ctschroeder** [comment]
I'll send a separate email about the ANNIS Visualizers and API.

**Comment by lukehollis** [comment]
Yes, the resolver can ingest the corpora metadata, but @amir-zeldes mentioned a query to get the list of corpus names to ingest corpora metadata, document names, document metadata, and html visualizations from ANNIS.  Right now the list of corpus names is preset with the Corpus objects in the database instead of being dynamically generated from a query to ANNIS.

**Comment by ctschroeder** [comment]
I understand. There are several issues in this thread: your request to put the ANNIS string or corpus URN in the corpus metadata, the API re the visualizations, and the original question about the flag. Regarding the flag: that info is already in the corpus metadata. Every corpus has the project field with scriptorium in it (and if it doesn't we can add it --you should still be able to test the feature on the ones that have it).  

I am still struggling to understand why we need to go in and add more corpus level metadata (a string or corpus urn) since the corpora do have unique names.  And the aforementioned "flag" exists (project = /.*scriptorium.*/) so the corpora can be determined automatically at ingest. 

Regarding the visualizations: I'm sure Amir will be able to tell you tomorrow if the API supplies the names of the visualizations currently. 

If it does not, you will need to set up the ingest to add the visualizations manually. I am sending a separate email on this, but to be blunt: we are out of time.  Republishing the corpora is extremely time consuming, and we no longer have time to go in and add more metadata, re publish, etc. nor do we have time to wait on the API if that aspect is not open.

**Comment by amir-zeldes** [comment]
Hi all, I have tested the ANNIS API for resolver entries – it was originally intended to deliver results for a specific:

 

-        Corpus

-        Namespace (nodes, edges and annotations can be partitioned into namespaces in ANNIS, which are then visible to a visualizer while ignoring others)

-        Objects triggering the visualizer (one of: node OR edge OR NULL – meaning always display)

 

This would have been a problem, since our corpora have different namespaces (the Shenoute annotations usually have a shenoute: namespace, but AP has ap:, I think). Fortunately, it seems inputting NULL in namespace gives you resolver entries that don’t have namespace restrictions, and htmldoc belongs to these. Therefore, the following works for our scenario:

 

https://corpling.uis.georgetown.edu/annis-service/annis/query/resolver/shenoute.fox/NULL/node

 

This gives us all the automatically displayed annotations, which includes the HTML visualizers, but also the default key-word-in-context view. The output looks like this, and you will need to filter for those entries that have the visType htmldoc, ignoring all others:

 

<resolverEntries>

<resolverEntry>

<displayName>kwic</displayName>

<id>1</id>

<mappings/>

<order>-1</order>

<visType>kwic</visType>

<visibility>permanent</visibility>

</resolverEntry>

<resolverEntry>

<corpus>shenoute.fox</corpus>

<displayName>analytic view (document)</displayName>

<id>252</id>

<mappings>

<entry>

<key xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">config</key>

<value xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">analytic</value>

</entry>

</mappings>

<order>100</order>

<visType>htmldoc</visType>

<visibility>hidden</visibility>

</resolverEntry>

<resolverEntry>

<corpus>shenoute.fox</corpus>

<displayName>diplomatic text (document)</displayName>

<id>253</id>

<mappings>

<entry>

<key xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">config</key>

<value xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">dipl</value>

</entry>

</mappings>

<order>101</order>

<visType>htmldoc</visType>

<visibility>hidden</visibility>

</resolverEntry>

<resolverEntry>

<corpus>shenoute.fox</corpus>

<displayName>normalized text (document)</displayName>

<id>254</id>

<mappings>

<entry>

<key xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">config</key>

<value xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">norm</value>

</entry>

</mappings>

<order>102</order>

<visType>htmldoc</visType>

<visibility>hidden</visibility>

</resolverEntry>

</resolverEntries>

**Comment by lukehollis** [comment]
Since we decided in our Monday conversation not to ingest the Github, ANNIS code, or other

**Comment by ctschroeder** [comment]
This is @amir-zeldes's bailiwick.  I'm fine with implementing the automatic ingest of visualization types in a later iteration.  My one question:  do the manual configurations have to be set every time a corpus is ingested, even if it's an ingest of a new version of an existing corpus?

**Comment by lukehollis** [comment]
The manual configurations (Github links, ANNIS code, HTML visualization formats, etc) for the 9 corpora have to be set once and not updated every time an ingest occurs.

**Comment by ctschroeder** [comment]
ok great.

**Comment by amir-zeldes** [comment]
I see this is closed already - I just wanted to add confirmation from my bailiwick that we (myself and the villagers) are all fine with this ;)

**Comment by ctschroeder** [comment]
Thanks, Amir.  Sorry if I closed prematurely.  Was trying to clear the deck.  Glad I didn't sweep away any disgruntled villagers in the process.  :)
