### ISSUE TITLE
404 page does not always appear when a page does not exist

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/cts#87]
The 404 page does not appear when a page does not exist.  For example, a colleague tried to send people to our site using this URL:  http://data.copticscriptorium.org/texts/ap/ap005unidsense .  (I'm not sure where she got the URL -- it is not a valid one.  But at any rate, it proved a good test case.)  The site just spins and spins and never resolves.  It should give a 404.

**Comment by amir-zeldes** [comment]
This can probably be closed: URLs like http://data.copticscriptorium.org/texts/ap/ap005unidsense now do not hang, but revert to the main menu, since they are not URN URLs. An invalid URN URL will produce the missing URN message, i.e. it should be:

http://data.copticscriptorium.org/urn:ap005unidsense

Either way, CTS does not crash.
