### ISSUE TITLE
Search URLs should include field value only and not database IDs

### ISSUE THREAD

**Issue by amir-zeldes** [CopticScriptorium/cts#88]
Currently search URLs generated when the faceted search is clicked on include both field values and IDs, e.g.:

```
http://data.copticscriptorium.org/filter/author=30995:Shenoute
```

This ID is not predictable for an external API trying to find all documents by Shenoute. The URLs should be changed to look like this:

```
http://data.copticscriptorium.org/filter/author=Shenoute
```

**Comment by dcbriccetti** [comment]
It might be easier to leave that alone and add this:
http://data.copticscriptorium.org/search?author=Shenoute

**Comment by amir-zeldes** [comment]
That sounds fine. 

The background is this: Predictable search URLs will allow us to link searches directly from certain ANNIS annotations, thanks to a new feature that is now being tested which allows generation of dynamic links based on annotation values.

**Comment by dcbriccetti** [comment]
OK to implement this with a redirect? The new location for
search?<key>=<value>  (e.g., search?author=Shenoute)
would be set to 
filter/key=number:value
where number is the currently used ID in the search internals.

307 Temporary Redirect       (https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html)

The requested resource resides temporarily under a different URI. Since the redirection MAY be altered on occasion, the client SHOULD continue to use the Request-URI for future requests. This response is only cacheable if indicated by a Cache-Control or Expires header field.

The temporary URI SHOULD be given by the Location field in the response. Unless the request method was HEAD, the entity of the response SHOULD contain a short hypertext note with a hyperlink to the new URI(s) , since many pre-HTTP/1.1 user agents do not understand the 307 status. Therefore, the note SHOULD contain the information necessary for a user to repeat the original request on the new URI.

If the 307 status code is received in response to a request other than GET or HEAD, the user agent MUST NOT automatically redirect the request unless it can be confirmed by the user, since this might change the conditions under which the request was issued.

**Comment by dcbriccetti** [comment]
Try it!
http://52.39.198.200/api/search?corpus=besa.letters&corpus=shenoute.a22&author=besa

**Comment by amir-zeldes** [comment]
This is great, because you can also generate searches that are not currently in the faceted search categories (drop downs). @ctschroeder check this out:

http://52.39.198.200/api/search?objectType=codex

Thanks Dave!

**Comment by dcbriccetti** [comment]
I’m rethinking the my recommendation to call this .../api/search?.... The API returns JSON and is meant to be called by a computer program. The result of this is meant to be seen by humans (even though the link may be generated by a program. Perhaps the answer is simply to remove /api from the URL. Thoughts?

**Comment by amir-zeldes** [comment]
Yeah, sure, removing api from the URL makes sense to me

**Comment by ctschroeder** [comment]
Hi. Thank you so much for all your work on this. 
I agree, removing api from the URL makes sense.  
When I click on the links upthread, they work well.  The resulting website's final resolved URL though still has the numbers.  Am I not understanding something?

**Comment by dcbriccetti** [comment]
Prior to this enhancement, there was no actual searching happening in real time. Everything was already “pre-searched” during the ingestion. Think of those numbers as pointers to the pre-searched results. They change after a new ingestion. I doubt they were intended for users to even be aware of them. The change I made does the search, and then through redirection, sets the filters as the would have been set had the search arguments been set in the webapp.

Now I’m think that adding the [/api]/search URL is unnecessarily complex. Why not use the syntax Amir suggest at the top:
http://data.copticscriptorium.org/filter/author=Shenoute

**Comment by ctschroeder** [comment]
Thanks for the info. Honestly I don't care as long as the numbers aren't in there.  The numbers mean that the URLs are totally impermanent and change with every ingest, so people can't save the URLs.  (The stability of the URLs is my main concern.)

**Comment by amir-zeldes** [comment]
Yeah, agreed - although URLs are not really guaranteed like URNs, it would be nice not to have something totally unpredictable in there.

**Comment by ctschroeder** [comment]
Yeah I'm thinking for basic bookmarking.
