### ISSUE TITLE
Group and order metadata

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/cts#92]
Group and order metadata in logical sequence tbd by @amir-zeldes and @ctschroeder.  Any metadata fields not in specific groups or not given an order sequence will be listed last in alphabetical order

**Comment by dcbriccetti** [comment]
Any details for this yet?

**Comment by amir-zeldes** [comment]
Hi all,

This is a slightly complicated topic. The question of what is the desirable order is one issue, the question of how it is indicated and how metadata are grouped is another. I'll talk about the 2nd, since the order could be changed at any point if we decide.

In ANNIS, metadata are sorted alphabetically by name, but there is a second level of abstraction we haven't used yet, which is namespaces. Namespaces can be applied to any positional annotation, and that's used, among other things, to display multiple grid views in ANNIS. But actually, namespaces can also be applied to metadata. When the metadatum namespace is NULL, the namespace is ignored.

To see what it looks like, I've added a namespace 'test' to the author metadatum of to_aphthonia. You can see the namespace appear in the REST API call here:

https://corpling.uis.georgetown.edu/annis-service/annis/meta/doc/besa.letters/to_aphthonia

You can also see it ANNIS by opening the corpus explorer (i button next to the corpus name) and looking at the metadata for that document. Right now there is an entry test:author (I'll revert this later).

Searches can still work as before, since you can always query without namespaces:

norm & meta::author="Besa"

Or with:

norm & meta::test:autho="Besa"

We could use namespaces to group metadata. The main advantage would be that the groups are actually in the data model, and they'd sort the same way in ANNIS. Disadvantages are:

  * We'd have to manually or semi-automatically put namespace info into all of our data
  * If we don't pick namespaces that alphabetize the way we want, we still have an ordering problem across groups (this can be avoided by choosing particular namespace names)
  * There is no way to centrally decide we want to put 'author' before 'title' tomorrow: we would literally need to change all corpora, and in fact we could make different decisions for each corpus (this can also be seen as an advantage).

The alternative to all this, is to have some administration interface in the cts software that determines metadata order. That's easier to apply across corpora, but it doesn't affect the order in ANNIS and I assume we'd make it global (no different orders per corpus). Then again, it also doesn't alter the display in ANNIS and requires no editing of our corpora, so it's probably the cheaper option.

Let me know what you think!

**Comment by ctschroeder** [comment]
I would vote for admin interface in cts.  I am less wedded to complete symmetry between ANNIS and the cts system.  Assuming this is not too complex.  I need to re-look at the budget, though, and get a sense of the time this would take before signing off on it.

**Comment by ctschroeder** [comment]
We have decided to do this within the cts urn resolver interface.  It should be done with a configurable file, not in the code.

**Comment by dcbriccetti** [comment]
Perhaps we could expand the scope of this table,
![screen shot 2016-12-12 at 5 14 58 pm](https://cloud.githubusercontent.com/assets/55099/21123626/a49d098c-c08e-11e6-99ac-faba74b8c458.png)
which now identifies the “searchable” metadata, the order in which they appear here,
![screen shot 2016-12-12 at 5 17 24 pm](https://cloud.githubusercontent.com/assets/55099/21123678/00119c24-c08f-11e6-8121-144d0634bd72.png)
and whether they are splittable.

**Comment by amir-zeldes** [comment]
Seems reasonable; then from a certain number or specific value in 'order' they would not be displayed in the search. Note we need two distinct 'orders' - order in the menu bar (and whether to display) and order in the bottom of a selected document.

**Comment by dcbriccetti** [comment]
Let’s consider a new table, then (unless you have another way in mind, like a file in the file system).
MetaOrder, or something, with ID, name and order columns. Have we abandoned grouping? How do you want to get the initial set of data to me. A spreadsheet or CSV, file?

**Comment by amir-zeldes** [comment]
A table sounds fine, as long as we have some way of editing it. If it's a hassle to make an interface for that then a file is also a possibility. I'd expect the default order to be alphabetic for unlisted items, and for unlisted items to appear after all listed items have been arranged (so unlisted items get min priority). And then we can do proof of concept just by specifying 'author' and 'title' as the first two. @ctschroeder : I'm not passionate about any particular order, feel free to suggest.

**Comment by dcbriccetti** [comment]
The Django admin interface gives you a simple way to change a table. I’ll go this way.

**Comment by dcbriccetti** [comment]
This seems to be working nicely, but the display is flowing the metadata names across rows, instead of in columns. Notice that author is first on the left, followed by title on the right. Is this what you want?
<img width="783" alt="screen shot 2016-12-13 at 1 44 08 pm" src="https://cloud.githubusercontent.com/assets/55099/21160612/5314d098-c13a-11e6-8dab-42fae3e54596.png">

The table:
<img width="218" alt="screen shot 2016-12-13 at 1 54 30 pm" src="https://cloud.githubusercontent.com/assets/55099/21160980/bd60070a-c13b-11e6-8d13-1d0fdeb91932.png">

**Comment by ctschroeder** [comment]
not great but not a big deal -- I think the display has always flowed 
across not down columns.

**Comment by dcbriccetti** [comment]
Any interest in lining things up better?
<img width="581" alt="screen shot 2016-12-13 at 2 03 48 pm" src="https://cloud.githubusercontent.com/assets/55099/21161357/0fb08df8-c13d-11e6-8db5-8208d079b989.png">

**Comment by ctschroeder** [comment]
Still flowing across rows but now the field is on a line above the data entry? I'm confused.

**Comment by dcbriccetti** [comment]
Doesn’t grab you? I’ll leave it alone. The fact that the metadata values don’t line up has bothered me.

**Comment by dcbriccetti** [comment]
OK, this is running in the test system. You can add more rows:
<test server>/admin/texts/metaorder/

**Comment by ctschroeder** [comment]
> Ok you can deploy 7:30-8:30. Seems to work. 

Only prob I noticed was that I couldn't run an ingest from my phone on the test server. Ingest interface says there are no corpora. Corpora interface shows all the corpora. Totally confused as to what is going on. Perhaps not all the code is up to date on test server? Or there is a mobile problem?

**Comment by dcbriccetti** [comment]
Odd. Can you get to a desktop? Works fine for me in two browsers. I can try mobile later.

**Comment by ctschroeder** [comment]
Works on desktop. Go ahead. Don't worry about mobile for now.  Many thanks!!!

**Comment by dcbriccetti** [comment]
Production system is now updated. Have fun!

**Comment by amir-zeldes** [comment]
Ordering looks good, thanks!
